openapi: 3.0.3
info:
  title: Bulletin Board APIs
  version: 1.0.0

components:
  schemas:
    NewEvent:
      description: "An event is an added point on the bulletin board - New Event is object requested during creation of an event"
      type: object 
      required: 
        - message 
          gid
          uid
      properties: 
        uid:
          type: string
          example: "Mongo DB Object ID for user sending request"
        gid:
          type: string
          example: "AX5HG"
        message:
          type: string 
          example: "Aritra needs to get a life"
          
    ExistingEvent:
      description: "Object needed for deletion of an event within bulletin board of a group"
      type: object 
      required: 
        - _id
          gid
          uid
      properties: 
        uid:
          type: string
          example: "Mongo DB Object ID for user sending request"
        gid:
          type: string
          example: "AX5HG"
        _id:
          type: string
          example: "Mongo DB Object ID for the Event being edited/deleted"
    UserGroupDetails:
      description: "Useful for "
    

        
        
paths:
  /bulletinBoard/{uid}/addEvent:
    post:
      description: Add a new event for the bulletin board
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: Successfully added the event for the Bulletin Board for a specific gid
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
                    
  /bulletinBoard/{uid}/getEvents:
    get: 
      description: Get details of the Bulletin Board for a particular gid, with JWT sent to ensure we are within a login session
      parameters:
        - in: path
          required: true
          name: uid
          schema:
            type: string
            example: Mongo DB Object ID for User
        - in: query
          required: true
          name: gid
          schema: 
            type: string
            example: AX67F (Some group ID)
          
      responses:
        '200':
          description: Successfully returned all the events on a bulletin board
      

  /bulletinBoard/{uid}/deleteEvent:
    post:
      description: Add a new expense or record a mutual payment 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: Successfully added the transaction 
        
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string