openapi: 3.0.3
info:
  title: Bulletin Board APIs
  version: 1.0.0

components:
  schemas:
    Event:
      description: "An event is an added point on the bulletin board with JWT to ensure we are still within a logged in session"
      type: object 
      required: 
        - message 
          gid
      properties: 
        message:
          type: string 
          example: "Aritra needs to get a life"
        gid: 
          type: string
          example: "AX67F (Some group ID)"
        
        
paths:
  /board:
    get: 
      description: Get details of the Bulletin Board for a particular gid, with JWT sent to ensure we are within a login session
      parameters:
        - in: header
          name: JWT Token
          content: 
            string:
              schema:
                type: string
                properties:   
                  message:
                    type: string
      responses:
        '200':
          description: Successfully returned all the events on a bulletin board

    post: 
      description: Get details of the Bulletin Board for a particular gid, with JWT sent to ensure we are within a login session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                discourdUserId: 
                  type: string
                  example: "test#123"
                discordServerId: 
                  type: string
                  example: "18097086956959"
           
      
      responses:
        '200':
          description: Successfully returned all the events on a bulletin board
      
  /board/addEvent:
    post:
      description: Add a new event for the bulletin board
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                discourdUserId: 
                  type: string
                  example: "test#123"
                discordServerId: 
                  type: string
                  example: "18097086956959"
                message:
                  type: string
                  example: "Testing Bulletin Board"
      responses:
        '200':
          description: Successfully added the event for the Bulletin Board for a specific roommate group on the basis of our discord server id
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string
  /board/deleteEvent:
    delete:
      description: Delete an event from the bulletin board
      requestBody:
        content:
          application/json:
            schema:
              properties:
                discourdUserId: 
                  type: string
                  example: "test#123"
                discordServerId: 
                  type: string
                  example: "18097086956959"
                eventId:
                  type: string
                  example: "986969"
      responses:
        '200':
          description: Successfully added the event for the Bulletin Board for a specific roommate group on the basis of our discord server id
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string