openapi: 3.0.0
info:
  version: 1.0.0
  title: Calendar APIs
  description: List of APIs related to chore management with the Calendar APIs

components:
 schemas:
  Chore:
    type: object
    required:
      - name
        duration
    properties: 
      name:
        type: string
      start:
        type: string   # time in HH:MM. 24 hour
      duration:
        type: number   # in minutes, must be included if time_of_day_start is specified
      preferred_days:
        type: array    # array of days of the week
        items:
          type: string
        
  Event:
    type: object
    properties:
      name: 
        type: string
      start:
        type: string  
      end:
        type: string # in minutes
      associated_with:
        type: string  # id
      associated_with_name:
        type: string
      gcal_event_id:
        type: string  
    
  Calendar: 
    type: object
    required:
      - gid
    properties:
      gid:
        type: string
      events:
        type: array
        items:
          $ref: '#/components/schemas/Event'



paths:
# ----------- Chore APIs --------------
  /calendar/{serverId}/createChore:
    post:
          description: Create a new chore
          parameters:
            - name: serverId
              in: path
              required: true
              description: Server ID of the discord server
              schema:
                type: string
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Chore'
          responses:
            '200':
              description: Successfully created a new chore

            '400':
              description: Invalid request
              content:
                application/json:
                  schema:
                    type: object
                    properties:   
                      message:
                        type: string

  /calendar/{serverId}/getChores:
    get:
      description: Get a list of all the chores
      parameters:
        - name: serverId
          in: path
          required: true
          description: Server ID of the discord server
          schema:
            type: string
      responses:
        '200':
          description: Successfully returned a list of chores for the roommate group
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Chore'
                  
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string

  /calendar/{serverId}/deleteChore:
    delete:
      description: Delete chore
      parameters:
        - name: serverId
          in: path
          required: true
          description: Server ID of the discord server 
          schema:
            type: string
        - name: choreid
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully returned a list of chores for the roommate group
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string

# --------------- Calendar APIs ---------------

  /calendar/{gid}/getCalendar:
    get:
      description: Get calendar for current week, from Sunday to Saturday
      parameters:
        - name: gid
          in: path
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: Successfully returned Calendar
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:   
                  message:
                    type: string



