openapi: 3.0.3
info:
  version: V1
  title: Managemate - OpenAPI 3.0
  description: |-
    This is the documentation for Managemate based on OpenAPI 3.0 specification. 
  termsOfService: http://swagger.io/terms/
servers:
  - url: localhost:3000
tags:
  - name: User
    description: User Actions like login and signup
    
  - name: Roommate Group
    description: Actions that edit the RoommateGroup
    
paths:
  /auth/register:
    post:
      tags:
        - User
      summary: Sign up a new user in
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: Successful operation returns a Mongo Object ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResp'          
        '400':
          description: Invalid Login
        '404':
          description: User not found
        '405':
          description: Validation exception
    
  /auth/login:
    post:
      tags:
        - User
      summary: Log a new user in
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: Successful operation returns a JWT
          content:
            application/json:
              schema:
                type: string
                example: xxxxx.yyyyy.zzzzz        
        '400':
          description: Invalid Login
        '404':
          description: User not found
        '405':
          description: Validation exception
          
  /roommateGroup/create:
    post:
      tags:
        - Roommate Group
      summary: Create a Roommate group 
      operationId: create
      parameters:
        - in: header
          name: user
          description: JWT Token
          schema:
            $ref: '#/components/schemas/JWTUser'
      requestBody:
        description: This will only create the group, the creator needs to be added to the group
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReq'
        required: true
      responses:
        '200':
          description: Successful operation returns a group id 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateResp'          
        '400':
          description: Could not create new roommate group!
        '404':
          description: "Request timed out: invalid roommate group creation!"
          
  /roommateGroup/join:
    post:
      tags:
        - Roommate Group
      summary: Join a Roommate group 
      operationId: join
      parameters:
        - in: header
          name: user
          description: JWT Token
          schema:
            $ref: '#/components/schemas/JWTUser'
      requestBody:
        description: Adding someone to a roommate group
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateResp'
        required: true
      responses:
        '200':
          description: Successful operation lets us know that we have joined the group
        '400':
          description: Could not join new roommate group!
    
  /roommateGroup/leave:
    post:
      tags:
        - Roommate Group
      summary: Leave a Roommate group 
      operationId: leave
      parameters:
        - in: header
          name: user
          description: JWT Token
          schema:
            $ref: '#/components/schemas/JWTUser'
      requestBody:
        description: Removing someone from a roommate group
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateResp'
        required: true
      responses:
        '200':
          description: Successful operation lets us know that we have joined the group
        '400':
          description: Could not join new roommate group!
          
components:
  schemas:
    JWTUser:
      type: object 
      properties:
        _id:
          type: string
          example: <MongoDB Object _id>
        name:
          type: string
          example: John
        
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: '12345'
      
    CreateResp:
      type: object
      properties:
        gid:
          type: string
          example: ax5f3
          
    FormObject:
      type: object
      properties:
        name: 
          type: string
          example: Abhishek Marda
        email:
          type: string
          example: amarda@gmail.com
        groupName: 
          type: string
          example: Landfair Group
        uid:
          type: string
          example: <Insert MongoDB default _id for this user>
    
    CreateReq:
      type: object
      properties:
        groupName:
          type: string
          example: Landfair Group
      
    User:
      type: object
      properties:
        name:
          type: string
          example: John
        
        email:
          type: string
          example: john@email.com
        password:
          type: string
          example: '12345'
          
    SignupResp:
      type: object
      properties:
        user:
          type: string
          example: "5099803df3f4948bd2f98391"
      
   
     
